// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using MythChat.ApiService.Kiota.Client.Chat.Ask.Item;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace MythChat.ApiService.Kiota.Client.Chat.Ask {
    /// <summary>
    /// Builds and executes requests for operations under \chat\ask
    /// </summary>
    public class AskRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the MythChat.ApiService.Kiota.Client.chat.ask.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        public WithChannelItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("channel", position);
            return new WithChannelItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new AskRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AskRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/chat/ask", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new AskRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AskRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/chat/ask", rawUrl) {
        }
    }
}
